In [3]:
# #Importando las librerias necesarias para el analisis de la GEIH
import pandas as pd
import numpy as np

In [4]:
df_emicron=pd.read_csv('https://raw.githubusercontent.com/niconomist98/DataAnalyticsUQ/refs/heads/main/Datos/EMICRON/emicron_identificacion.csv', encoding='latin', sep= ',')

In [5]:
total_micronegocios_agricultura = df_emicron[df_emicron['GRUPOS12'] == 1]['F_EXP'].sum()
print("Total de micronegocios en el sector de agricultura:", total_micronegocios_agricultura)

Total de micronegocios en el sector de agricultura: 1138758.1274708195

In [6]:
df_emicron['GRUPOS12'].unique()

array([ 3,  1,  5,  7,  6,  9,  4, 12, 11,  8,  2, 10, 13])

In [26]:
#datos miembros del congreso

df=pd.read_csv('https://unitedstates.github.io/congress-legislators/legislators-current.csv')
df["birthday"]
df["age"]= 2024 - pd.to_datetime(df["birthday"]).dt.year
df[["age","birthday"]]

     age    birthday
0     66  1958-10-13
1     64  1960-05-25
2     83  1941-09-08
3     69  1955-10-20
4     72  1952-07-21
..   ...         ...
533   57  1967-08-25
534   49  1975-03-28
535   52  1972-04-13
536   50  1974-04-20
537   42  1982-10-22

[538 rows x 2 columns]

In [19]:
df['type'].unique()

array(['sen', 'rep'], dtype=object)

In [28]:
promedio_edad_estado = df.groupby(["state"])["age"].mean().sort_values(ascending=True)
promedio_edad_estado

state
PR    33.000000
MP    49.000000
AZ    50.400000
CO    50.500000
NM    51.000000
DE    52.333333
IN    52.636364
NY    54.857143
MT    55.250000
UT    55.333333
PA    55.421053
RI    55.500000
FL    55.966667
MO    56.200000
NH    56.250000
NC    56.562500
TX    56.717949
MI    56.733333
OK    57.285714
OH    57.352941
AL    57.444444
WA    57.500000
MN    57.800000
VI    58.000000
AK    58.000000
CA    58.222222
KS    58.333333
VA    58.461538
NJ    58.571429
GA    59.000000
IA    59.166667
NE    59.400000
LA    60.000000
SC    60.000000
SD    60.333333
WI    60.700000
IL    60.736842
MD    60.900000
KY    61.375000
MA    61.636364
AR    61.833333
GU    62.000000
ND    62.000000
HI    62.250000
OR    62.625000
NV    62.666667
TN    62.800000
MS    65.166667
WV    65.500000
ME    65.750000
CT    66.571429
WY    68.000000
ID    69.750000
VT    72.000000
AS    77.000000
DC    87.000000
Name: age, dtype: float64

In [30]:
micronegocios_por_dpto = df_emicron.groupby(["COD_DEPTO",'P35'])["F_EXP"].sum()
micronegocios_por_dpto

COD_DEPTO  P35
5          1      401961.465988
           2      228065.054284
8          1      203052.166264
           2      127459.192128
11         1      370414.355785
           2      218597.578012
13         1      237817.472299
           2       89256.882936
15         1       64788.375168
           2       47304.823258
17         1       57810.647554
           2       27679.193558
18         1       33905.164393
           2       15187.450504
19         1      153569.363753
           2       87585.021376
20         1      100135.189800
           2       53543.138605
23         1      212544.942870
           2       99508.457678
25         1      152633.806724
           2       68092.478848
27         1       21019.762856
           2       10876.912625
41         1       56820.698162
           2       30260.144557
44         1       69470.742444
           2       51573.204613
47         1      158680.430585
           2       61369.107902
50         1       63151.505418
           2       43425.064565
52         1      252674.791143
           2      163404.046726
54         1       71633.458998
           2       46762.417691
63         1       21066.559083
           2       16095.311503
66         1       46357.246643
           2       25972.155798
68         1      202893.485065
           2       96198.312413
70         1      118310.949994
           2       41727.424606
73         1       85667.510004
           2       37552.765464
76         1      262883.396310
           2      187779.989543
88         1        2061.471444
           2         650.468304
Name: F_EXP, dtype: float64

In [31]:
df_emicron

,DIRECTORIO,SECUENCIA_P,SECUENCIA_ENCUESTA,COD_DEPTO,AREA,CLASE_TE,P35,P241,MES_REF,P3031,P3032_1,P3032_2,P3032_3,P3033,P3034,P3035,P3000,GRUPOS4,GRUPOS12,F_EXP
0,7627444,1,1,44,NaN,2,2,33,ENERO,2,NaN,NaN,NaN,2,240,2,2,2,3,60.050515
1,7627446,1,1,44,NaN,2,1,31,ENERO,2,NaN,NaN,NaN,2,166,2,2,1,1,86.341075
2,7627449,1,1,68,NaN,1,2,42,ENERO,2,NaN,NaN,NaN,2,60,2,2,3,5,139.884518
3,7627453,1,2,68,NaN,1,2,41,ENERO,2,NaN,NaN,NaN,2,60,2,2,4,7,168.635440
4,7627456,1,3,68,NaN,1,1,18,ENERO,2,NaN,NaN,NaN,2,9,2,2,4,6,64.659273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78496,8038070,1,3,13,NaN,1,1,24,DICIEMBRE,2,NaN,NaN,NaN,2,48,1,2,4,7,362.509123
78497,8038071,1,1,13,NaN,2,1,30,DICIEMBRE,2,NaN,NaN,NaN,2,48,2,2,1,1,158.805116
78498,8038073,1,1,13,NaN,2,1,66,DICIEMBRE,2,NaN,NaN,NaN,2,500,2,2,1,1,57.451130
78499,8038074,1,3,13,NaN,2,1,71,DICIEMBRE,2,NaN,NaN,NaN,2,500,2,2,1,1,93.355386
78500,8038075,1,1,13,NaN,2,1,64,DICIEMBRE,2,NaN,NaN,NaN,2,480,2,2,1,1,98.197081