<a href="https://colab.research.google.com/github/niconomist98/DataAnalyticsUQ/blob/main/Notebooks/02-%20GEIH24_Manipulacion_tablas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div style="text-align: center; color: green;">
    <h1>Indicadores de mercado laboral mediante la Metodología DANE: Exploración y análisis descriptivo de los resultados de la GEIH 2024 (Diciembre)</h1>
</div>

## Importando librerias

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

## Obtener directorio de trabajo actual (Opcional)

In [2]:
current_working_directory = Path.cwd()
current_working_directory

PosixPath('/content')

## Leer los modulos  necesarios para el calculo de los indicadores de Mercado Laboral:
* Caracteristicas generales, seguridad social en salud y educacion
* Ocupados
* Fuerza de trabajo
* No ocupados

In [ ]:
#Caracteristicas generales, seguridad social en salud y educacion

# Links a los conjuntos de datos
url_cgsse = 'https://raw.githubusercontent.com/niconomist98/DataAnalyticsUQ/main/Datos/GEIH2024/CGSSE.CSV'
url_ocupados = 'https://raw.githubusercontent.com/niconomist98/DataAnalyticsUQ/main/Datos/GEIH2024/Ocupados.CSV'
url_ft = 'https://raw.githubusercontent.com/niconomist98/DataAnalyticsUQ/main/Datos/GEIH2024/Fuerza%20de%20trabajo.CSV'
url_desocupados = 'https://raw.githubusercontent.com/niconomist98/DataAnalyticsUQ/main/Datos/GEIH2024/No%20ocupados.CSV'

# CGSSE
df_cgsse = pd.read_csv(url_cgsse, encoding='latin-1', sep=';', 
                       low_memory=False)

#Ocupados
df_ocupados=pd.read_csv(url_ocupados,encoding='latin-1',sep=';',
                        low_memory=False)

#Fuerza de trabajo
df_ft=pd.read_csv(url_ft,
                  encoding='latin-1',sep=';',low_memory=False)
#No ocupados
df_desocupados=pd.read_csv(url_desocupados,encoding='latin-1',
                           sep=';',low_memory=False)

## Revisar que los  modulos esten cargados correctamente

In [7]:
df_cgsse

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18
0,20240730,7,2024,7858603,1,1,1,10,NaN,2,...,2.0,NaN,4.0,1.0,NaN,NaN,NaN,2.0,1.0,1.0
1,20240730,7,2024,7858603,1,2,1,10,NaN,2,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0
2,20240730,7,2024,7858603,1,3,1,10,NaN,2,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,2.0,1.0,1.0
3,20240730,7,2024,7858604,1,1,1,10,NaN,2,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0
4,20240730,7,2024,7858604,1,2,1,10,NaN,2,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,2.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69689,20240730,7,2024,7889227,1,1,1,10,88.0,1,...,2.0,NaN,8.0,4.0,714.0,5.0,714.0,2.0,1.0,1.0
69690,20240730,7,2024,7889227,1,2,1,10,88.0,1,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0
69691,20240730,7,2024,7889227,1,3,1,10,88.0,1,...,2.0,NaN,10.0,5.0,521.0,2.0,NaN,1.0,2.0,1.0
69692,20240730,7,2024,7889227,1,4,1,10,88.0,1,...,2.0,NaN,8.0,1.0,413.0,2.0,NaN,2.0,1.0,1.0
69693,20240730,7,2024,7889227,1,5,1,10,88.0,1,...,1.0,1.0,3.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df_cgsse['FEX_C18'].sum()

np.float64(51569604.99998947)

In [10]:
df_ft

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351
0,20240730,7,2024,7858603,1,1,1,50,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20240730,7,2024,7858603,1,2,1,50,NaN,2,...,NaN,NaN,1.0,3.0,NaN,1.0,2.0,NaN,NaN,NaN
2,20240730,7,2024,7858603,1,3,1,50,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20240730,7,2024,7858604,1,1,1,50,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20240730,7,2024,7858604,1,2,1,50,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55033,20240729,7,2024,7889226,1,2,1,50,88.0,1,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55034,20240730,7,2024,7889227,1,1,1,50,88.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55035,20240730,7,2024,7889227,1,2,1,50,88.0,1,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55036,20240730,7,2024,7889227,1,3,1,50,88.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55037,20240730,7,2024,7889227,1,4,1,50,88.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_ocupados

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P514,P515,P1881,P1882,P7240,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20240730,7,2024,7858603,1,1,1,60,NaN,2,...,1,1,13,50.0,3,1,480000.0,1,161,9211
1,20240730,7,2024,7858603,1,3,1,60,NaN,2,...,2,1,12,15.0,3,1,640000.0,47,4711,5221
2,20240730,7,2024,7858604,1,1,1,60,NaN,2,...,2,2,3,10.0,8,1,400000.0,47,4781,9520
3,20240730,7,2024,7858604,1,2,1,60,NaN,2,...,1,1,3,20.0,5,1,600000.0,3,312,6222
4,20240730,7,2024,7858605,1,1,1,60,NaN,2,...,1,1,12,25.0,3,1,700000.0,1,161,9211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29924,20240728,7,2024,7889224,1,1,1,60,76.0,1,...,1,1,5,90.0,8,1,1050000.0,97,9700,9111
29925,20240729,7,2024,7889226,1,1,1,60,88.0,1,...,1,1,10,15.0,8,1,3000000.0,77,7729,5249
29926,20240730,7,2024,7889227,1,1,1,60,88.0,1,...,1,1,11,10.0,3,1,1750000.0,61,6110,7422
29927,20240730,7,2024,7889227,1,3,1,60,88.0,1,...,1,1,11,10.0,3,1,2000000.0,55,5511,1411
29928,20240730,7,2024,7889227,1,4,1,60,88.0,1,...,1,1,11,10.0,3,1,1600000.0,55,5511,4224

In [12]:
df_desocupados

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P9460,P1519,P1883,P7422,P7422S1,OFICIO1_C8,OFICIO2_C8,RAMA2D_D_R4,RAMA4D_D_R4,P7440
0,20240730,7,2024,7858603,1,2,1,70,NaN,2,...,2.0,2,NaN,1,400000.0,.,9111,97.0,9700,NaN
1,20240730,7,2024,7858605,1,2,1,70,NaN,2,...,NaN,2,NaN,2,NaN,4224,NaN,NaN,NaN,NaN
2,20240730,7,2024,7858606,1,3,1,70,NaN,2,...,NaN,2,NaN,2,NaN,.,.,NaN,.,NaN
3,20240730,7,2024,7858607,1,2,1,70,NaN,2,...,2.0,2,NaN,2,NaN,.,9111,97.0,9700,NaN
4,20240730,7,2024,7858607,1,3,1,70,NaN,2,...,NaN,2,NaN,2,NaN,.,.,NaN,.,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25104,20240727,7,2024,7889223,1,4,1,70,76.0,1,...,2.0,2,NaN,2,NaN,.,8156,15.0,1522,NaN
25105,20240728,7,2024,7889224,1,2,1,70,76.0,1,...,2.0,2,NaN,1,98.0,.,9333,47.0,4752,NaN
25106,20240728,7,2024,7889224,1,3,1,70,76.0,1,...,2.0,2,NaN,2,NaN,5120,5120,96.0,9609,NaN
25107,20240729,7,2024,7889226,1,2,1,70,88.0,1,...,2.0,2,NaN,2,NaN,.,5223,46.0,4632,NaN
25108,20240730,7,2024,7889227,1,2,1,70,88.0,1,...,2.0,2,NaN,2,NaN,.,4120,85.0,8553,NaN

<div style="text-align: center; color: blue;">
    <h1>Analisis de la estructura de los datos y jerarquía de Modulos</h1>
</div>

Es fundamental identificar la jerarquia y la estructura de los distintos modulos GEIH24 antes de iniciar con el análisis de los datos y el calculo de los indicadores relevantes de mercado laboral.

Llaves

----
<div style="color: red;">
    <p> * DIRECTORIO : El directorio identifica la vivienda.
    <p> * SECUENCIA_P : La secuencia_p identifica el hogar.
    <p> * ORDEN :  La variable orden hace referencia a las personas.

</div>

-----------------------
1. **Caracteristicas generales, seguridad social en salud y educacion** : Este modulo contiene caracteristicas generales de la poblacion y datos relevantes de la muestra representativa (hogares, viviendas, personas) sobre la cual el dane recolecta informacion. Este es el modulo mas general y sera el modulo base a partir del cual iremos añadiendo los demas modulos.
----
2. **Fuerza de trabajo** : Contiene informacion relevante para el analisis de la fuerza de trabajo, aqui se encuentran todas las personas en edad de trabajar y a este modulo se deben unir el modulo ocupados y no ocupados para calcular las tasas de desempleo y ocupación
----
3. **Ocupados**: En este modulo solo se incluye informacion de personas que ,en el modulo fuerza de trabajo fueron identificadas como población ocupada.
----

4. **No ocupados**: En este modulo solo se incluye informacion de personas que ,en el modulo fuerza de trabajo fueron identificadas como población no ocupada (Desempleados).

<div style="text-align: center; color: green;">
    <h1>Exploracion de Modulos y Calculos base</h1>
</div>

<div style="text-align: center; color: blue;">
    <h1> 1. Caracteristicas generales, seguridad social en salud y educacion</h1>
    
   <a href="https://microdatos.dane.gov.co/index.php/catalog/819/data-dictionary/F63?file_name=Caracteristicas%20generales,%20seguridad%20social%20en%20salud%20y%20educacion">Diccionario de datos Caracteristicas generales, seguridad social en salud y educacion </a>
   
    
<a href=" https://microdatos.dane.gov.co/index.php/catalog/819/download/23306">Codificación de respuestas</a>
</div>

## Calcular población total

In [ ]:
PT =  df_cgsse['FEX_C18'].sum()
print(f' La población total de referencia para Colombia basado en el modulo cgsse de la GEIH y el factor de expansión es {PT}')

 La población total de referencia para Colombia basado en el modulo cgsse de la GEIH y el factor de expansión es 51787627.99999624

## Calcular población total : desagregación hombres y mujeres

In [ ]:
#P3271 : Cuál fue su sexo al nacer? Masculino: 1 Femenino: 2

PH = df_cgsse[df_cgsse['P3271']==1]['FEX_C18'].sum()
PM = df_cgsse[df_cgsse['P3271']==2]['FEX_C18'].sum()
print(f' Hombres : {PH}')
print(f' Mujeres:  {PM}')

 Hombres : 25186709.99999831
 Mujeres:  26600917.999997925

In [ ]:
PH/PT*100

48.63460825044959

In [ ]:
PM/PT*100

51.365391749550405

In [ ]:
#CALCULAR POBLACION TOTAL DEL QUINDIO
#DPTO : departamento , Quindio es el 63

PTQ = df_cgsse[df_cgsse['DPTO']==63]['FEX_C18'].sum()
PTQ

603877.793353781

In [ ]:
#Calculando cantidad de hombres y de mujeres
PHQ = df_cgsse[(df_cgsse['DPTO']==63) & (df_cgsse['P3271']==1)]['FEX_C18'].sum()
PMQ = df_cgsse[(df_cgsse['DPTO']==63) & (df_cgsse['P3271']==2)]['FEX_C18'].sum()
print(f' Hombres del Quindio : {PHQ}')
print(f' Mujeres del Quindio:  {PMQ}')

 Hombres del Quindio : 277973.773110666
 Mujeres del Quindio:  325904.020243115

In [ ]:
#Porcentaje de hombres en el Quindio
PHQ/PTQ*100

46.03146136023178

In [ ]:
#Porcentaje de mujeres en el Quindio

PMQ/PTQ*100

53.96853863976823

## Calcular población en edad de trabajar

In [ ]:
# P6040 :  ¿cuántos años cumplidos tiene...?
df_cgsse[df_cgsse['P6040']>=15]['FEX_C18'].sum()

40377906.99999976

## Calcular población en edad de trabajar :Desagregación Hombres y Mujeres

In [ ]:
# P6040 :  ¿cuántos años cumplidos tiene...?
PETH=df_cgsse[(df_cgsse['P6040']>=15) & (df_cgsse['P3271']==1)]['FEX_C18'].sum()
PETM=df_cgsse[(df_cgsse['P6040']>=15) & (df_cgsse['P3271']==2)]['FEX_C18'].sum()
print(f' PET Hombres : {PETH}')
print(f' PET Mujeres:  {PETM}')

 PET Hombres : 19370847.000000313
 PET Mujeres:  21007059.99999944

<div style="text-align: center; color: blue;">
    <h1> 2. Fuerza de trabajo   </h1>
    
   <a href="https://microdatos.dane.gov.co/index.php/catalog/819/data-dictionary/F65?file_name=Fuerza%20de%20trabajo">Diccionario de datos fuerza de trabajo </a>
   
    
<a href=" https://microdatos.dane.gov.co/index.php/catalog/819/download/23306">Codificación de respuestas</a>
</div>

## Cantidad de personas en el dataset fuerza de trabajo : PET

In [ ]:
#PET : Poblacion en edad de trabajar ? 1: si
PET=df_ft[df_ft['PET']==1]['FEX_C18'].sum()
# Coincide con -> df_ft['FEX_C18'].sum()
print(f'Población en edad de trabajar {PET}')

Población en edad de trabajar 40377906.99999976

## PEA

In [ ]:
#FT: Pertenece a la PEA: .sum()si: 1
PEA=df_ft[(df_ft['FT']==1)]['FEX_C18'].sum()
print(f'Población Economicamente Activa {PEA}')

Población Economicamente Activa 25992581.54592417

## PEA : Desagregación hombres y mujeres

In [ ]:
## Calcule PEA de hombres y mujeres

## PEI

In [ ]:
#FFT Pertenece a la PEI  si:1
PEI=df_ft[(df_ft['FFT']==1)]['FEX_C18'].sum()
print(f'Población Economicamente Inactiva {PEI}')

Población Economicamente Inactiva 14385325.454075582

## PEI : Desagregación hombres y mujeres

In [ ]:
## Calcule PEI de hombres y mujeres

<div style="text-align: center; color: blue;">
    <h1> 3. Ocupados  </h1>
   
</div>

## Cantidad de personas en el dataset Ocupados : Poblacion ocupada

In [ ]:
#OCI : Ocupado ? 1:si
O=df_ocupados[(df_ocupados['OCI']==1)]['FEX_C18'].sum()
print(f'Población Ocupada {O}')

Población Ocupada 23620681.702875465

## Ocupados : Desagregación hombres y mujeres

In [ ]:
## Calcule poblacion ocupada de hombres y mujeres

<div style="text-align: center; color: blue;">
    <h1> 4. No Ocupados  </h1>
   
</div>

## Cantidad de personas en el dataset  No Ocupados : Poblacion en desempleo

In [ ]:
#OCI : Ocupado ? 1:si
D=df_desocupados[(df_desocupados['DSI']==1)]['FEX_C18'].sum()
print(f'Población No ocupada {D}')

Población No ocupada 2371899.843048705

## No Ocupados : Desagregación hombres y mujeres

In [ ]:
## Calcule poblacion  no ocupada de hombres y mujeres

<div style="text-align: center; color: green;">
    <h1>Calculo de indicadores de mercado laboral Diciembre 2024</h1>
</div>

En los calculos base obtuvimos :

* Poblacion total :
* Poblacion en edad de trabajar :
* Poblacion que no esta en edad de trabajar :
* Poblacion economicamente activa:
* Poblacion economicamente inactiva:
* Ocupados :
* No ocupados :

<div style="text-align: center; color: blue;">
    <h1> 1. Totales nacionales Diciembre 2021</h1>
</div>

# 1.1. Tasa de desempleo

In [ ]:
TD=D/PEA*100
print(f' Tasa de desempleo para diciembre de 2024 : {round(TD,1)}')

 Tasa de desempleo para diciembre de 2024 : 9.1

# 1.2. Tasa global de participacion

In [ ]:
TGP=PEA/PET*100
print(f' Tasa de global de participacion para Diciembre de 2024  : {round(TGP,1)}')

 Tasa de global de participacion para Diciembre de 2024  : 64.4

# 1.3. Tasa de ocupacion

In [ ]:
TO=O/PET*100
print(f' Tasa de ocupacion para Diciembre de 2024 {round(TO,1)}')

 Tasa de ocupacion para Diciembre de 2024 58.5

<div style="text-align: center; color: blue;">
    <h1> 2. Población ocupada según rama de actividad, Diciembre 2024 </h1>
</div>

In [ ]:
ocupados_por_rama = df_ocupados.groupby('RAMA2D_R4')['FEX_C18'].sum().reset_index()

print(ocupados_por_rama)

    RAMA2D_R4       FEX_C18
0           0  1.824447e+02
1           1  2.987963e+06
2           2  3.615528e+04
3           3  1.266357e+05
4           5  6.110968e+04
..        ...           ...
82         94  1.069059e+05
83         95  2.676146e+05
84         96  6.080387e+05
85         97  7.135436e+05
86         99  2.189950e+03

[87 rows x 2 columns]