In [1]:
# #Importando las librerias necesarias para el analisis de la GEIH
import pandas as pd
import numpy as np

In [2]:
#Leyendo los datos de la geih
df_cgsse = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/cgsse.CSV'
                       ,encoding='latin',sep=';'
                       )

df_o = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Ocupados.CSV'
                       ,encoding='latin',sep=';'
                       )

df_d = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/No%20ocupados.CSV'
                       ,encoding='latin',sep=';'
                       )

df_ft = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Fuerza%20de%20trabajo.CSV'
                       ,encoding='latin',sep=';'
                       )

/tmp/ipykernel_5834/4228185253.py:6: DtypeWarning: Columns (28,89,133,147,158) have mixed types. Specify dtype option on import or set low_memory=False.
  df_o = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Ocupados.CSV'
/tmp/ipykernel_5834/4228185253.py:14: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ft = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Fuerza%20de%20trabajo.CSV'

In [3]:
df_ft

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351
0,20250626,6,2025,8238974,1,1,1,50,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20250626,6,2025,8238974,1,2,1,50,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20250626,6,2025,8238975,1,1,1,50,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20250626,6,2025,8238975,1,2,1,50,NaN,2,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20250626,6,2025,8238975,1,3,1,50,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54445,20250626,6,2025,8283060,1,1,1,50,88.0,1,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54446,20250626,6,2025,8283060,1,2,1,50,88.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54447,20250626,6,2025,8283062,1,1,1,50,94.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54448,20250626,6,2025,8283062,1,2,1,50,94.0,1,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54449,20250626,6,2025,8283062,1,3,1,50,94.0,1,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_o

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20250626,6,2025,8238974,1,1,1,60,NaN,2,...,3,NaN,3.0,3,NaN,1,950000.0,1,113,6111
1,20250626,6,2025,8238974,1,2,1,60,NaN,2,...,3,NaN,4.0,5,NaN,1,NaN,1,113,6111
2,20250626,6,2025,8238975,1,1,1,60,NaN,2,...,3,NaN,10.0,3,NaN,1,700000.0,1,113,6114
3,20250626,6,2025,8238975,1,3,1,60,NaN,2,...,3,NaN,10.0,3,NaN,1,2000000.0,1,145,6122
4,20250626,6,2025,8238976,1,1,1,60,NaN,2,...,14,NaN,NaN,8,NaN,1,600000.0,1,122,6112
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29701,20250626,6,2025,8283057,1,3,1,60,41.0,1,...,8,NaN,25.0,5,NaN,1,3800000.0,85,8544,2310
29702,20250625,6,2025,8283058,1,1,1,60,NaN,1,...,14,NaN,NaN,2,NaN,1,3000000.0,71,7111,2161
29703,20250625,6,2025,8283058,1,2,1,60,NaN,1,...,3,NaN,10.0,1,NaN,1,1500000.0,47,4752,1420
29704,20250626,6,2025,8283060,1,2,1,60,88.0,1,...,3,NaN,10.0,8,NaN,1,500000.0,56,5619,7512
29705,20250626,6,2025,8283062,1,1,1,60,94.0,1,...,9,NaN,300.0,8,NaN,1,900000.0,3,312,6222

In [5]:
df_d

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P7360,P9460,P1519,P1883,P7422,P7422S1,OFICIO1_C8,OFICIO2_C8,RAMA2D_D_R4,RAMA4D_D_R4
0,20250626,6,2025,8238975,1,2,1,70,NaN,2,...,1.0,2.0,2,NaN,2,NaN,.,6112,1.0,0123
1,20250626,6,2025,8238978,1,1,1,70,NaN,2,...,1.0,2.0,2,NaN,2,NaN,.,9211,1.0,0161
2,20250626,6,2025,8238980,1,2,1,70,NaN,2,...,NaN,NaN,2,NaN,2,NaN,.,.,NaN,.
3,20250626,6,2025,8238981,1,2,1,70,NaN,2,...,NaN,NaN,2,NaN,2,NaN,.,.,NaN,.
4,20250626,6,2025,8238983,1,2,1,70,NaN,2,...,NaN,NaN,2,NaN,2,NaN,.,.,NaN,.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24739,20250626,6,2025,8283056,1,1,1,70,27.0,1,...,10.0,2.0,3,NaN,2,NaN,.,2341,85.0,8530
24740,20250626,6,2025,8283059,1,1,1,70,76.0,1,...,6.0,2.0,2,NaN,2,NaN,5223,5113,55.0,5511
24741,20250626,6,2025,8283060,1,1,1,70,88.0,1,...,9.0,2.0,2,NaN,2,NaN,.,9334,47.0,4711
24742,20250626,6,2025,8283062,1,2,1,70,94.0,1,...,NaN,NaN,2,NaN,2,NaN,.,.,NaN,.
24743,20250626,6,2025,8283062,1,3,1,70,94.0,1,...,NaN,NaN,2,NaN,2,NaN,.,.,NaN,.

In [6]:
df_cgsse

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18
0,20250626,6,2025,8238974,1,1,1,10,NaN,2,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0
1,20250626,6,2025,8238974,1,2,1,10,NaN,2,...,2.0,NaN,5.0,1.0,NaN,1.0,NaN,2.0,1.0,1.0
2,20250626,6,2025,8238975,1,1,1,10,NaN,2,...,2.0,NaN,3.0,3.0,NaN,NaN,NaN,2.0,1.0,1.0
3,20250626,6,2025,8238975,1,2,1,10,NaN,2,...,2.0,NaN,1.0,0.0,NaN,NaN,NaN,2.0,1.0,1.0
4,20250626,6,2025,8238975,1,3,1,10,NaN,2,...,2.0,NaN,1.0,0.0,NaN,NaN,NaN,1.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67851,20250626,6,2025,8283060,1,1,1,10,88.0,1,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0
67852,20250626,6,2025,8283060,1,2,1,10,88.0,1,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,2.0,1.0,1.0
67853,20250626,6,2025,8283062,1,1,1,10,94.0,1,...,2.0,NaN,3.0,3.0,NaN,NaN,NaN,2.0,1.0,1.0
67854,20250626,6,2025,8283062,1,2,1,10,94.0,1,...,2.0,NaN,3.0,2.0,NaN,NaN,NaN,1.0,2.0,1.0
67855,20250626,6,2025,8283062,1,3,1,10,94.0,1,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0

In [7]:
df_cgsse[['DIRECTORIO','SECUENCIA_P','ORDEN','FEX_C18']]

       DIRECTORIO  SECUENCIA_P  ORDEN    FEX_C18
0         8238974            1      1  67.484133
1         8238974            1      2  67.484133
2         8238975            1      1  54.337978
3         8238975            1      2  54.337978
4         8238975            1      3  54.337978
...           ...          ...    ...        ...
67851     8283060            1      1  47.033269
67852     8283060            1      2  47.033269
67853     8283062            1      1  32.850300
67854     8283062            1      2  32.850300
67855     8283062            1      3  32.850300

[67856 rows x 4 columns]

In [8]:
int(df_cgsse['FEX_C18'].sum())

#Calculo de la poblacion total de hombres
PH= df_cgsse[df_cgsse['P3271']==1]['FEX_C18'].sum()

#Calculo de la poblacion total de mujere
PM=df_cgsse[df_cgsse['P3271']==2]['FEX_C18'].sum()

print(f'Poblacion total de hombres: {PH}')
print(f'Poblacion total de mujeres: {PM}')

Poblacion total de hombres: 25304270.000003804
Poblacion total de mujeres: 26740731.000005245

In [9]:
int(df_o['FEX_C18'].sum())

23752952

In [10]:
int(df_ft['FEX_C18'].sum())

40653416

In [11]:
int(df_d['FEX_C18'].sum())

16900463

In [12]:
16900463+23752952

40653415

In [13]:
df_o_genero = pd.merge(df_o, df_cgsse[['DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'P3271']], 
                        on=['DIRECTORIO', 'SECUENCIA_P', 'ORDEN'], how='left')

In [14]:
#Calculo de hombres ocupados 
oh = df_o_genero[df_o_genero['P3271'] == 1]['FEX_C18'].sum()

#Calculo de mujeres ocupadas 

om = df_o_genero[df_o_genero['P3271'] == 2]['FEX_C18'].sum()

print (f'Hombres en empleo: {int(oh)}')
print (f'Mujeres en empleo: {int(om)}')

Hombres en empleo: 13860862
Mujeres en empleo: 9892089

In [15]:
df_d_genero = pd.merge(df_d, df_cgsse[['DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'P3271']], 
                        on=['DIRECTORIO', 'SECUENCIA_P', 'ORDEN'], how='left')

In [16]:
#Calculo de hombres ocupados 
dh = df_d_genero[df_d_genero['P3271'] == 1]['FEX_C18'].sum()

#Calculo de mujeres ocupadas 

dm = df_d_genero[df_d_genero['P3271'] == 2]['FEX_C18'].sum()

print (f'Hombres en desempleo: {int(dh)}')
print (f'Mujeres en desempleo: {int(dm)}')

Hombres en desempleo: 5637651
Mujeres en desempleo: 11262812

In [17]:
df_d.columns

Index(['PERIODO', 'MES', 'PER', 'DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'HOGAR',
       'REGIS', 'AREA', 'CLASE', 'FEX_C18', 'DPTO', 'FFT', 'DSI', 'P7250',
       'P7280', 'P7280S1', 'P744', 'P3074', 'P7260', 'P1806', 'P7430', 'P7440',
       'P7440S1', 'P7440S2', 'P7450', 'P7350', 'P7360', 'P9460', 'P1519',
       'P1883', 'P7422', 'P7422S1', 'OFICIO1_C8', 'OFICIO2_C8', 'RAMA2D_D_R4',
       'RAMA4D_D_R4'],
      dtype='object')