In [26]:
# #Importando las librerias necesarias para el analisis de la GEIH
import pandas as pd
import numpy as np

In [27]:
#Leyendo los datos de la geih
df_cgsse = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/cgsse.CSV'
                       ,encoding='latin',sep=';'
                       )

df_o = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Ocupados.CSV'
                       ,encoding='latin',sep=';'
                       )

df_d = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/No%20ocupados.CSV'
                       ,encoding='latin',sep=';'
                       )
df_ft = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Fuerza%20de%20trabajo.CSV'
                       ,encoding='latin',sep=';'
                       )

/tmp/ipykernel_3515/3175422324.py:6: DtypeWarning: Columns (28,89,133,147,158) have mixed types. Specify dtype option on import or set low_memory=False.
  df_o = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Ocupados.CSV'
/tmp/ipykernel_3515/3175422324.py:13: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ft = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Fuerza%20de%20trabajo.CSV'

# Calcular poblacion en edad de trabajar

In [28]:
PET = df_cgsse[df_cgsse['P6040']>=15]['FEX_C18'].sum()
print(f'Poblacion en edad de trabajar: {PET}')

Poblacion en edad de trabajar: 40653416.00000409

# poblacion que no esta en edad de trabajar

In [29]:
PNET = df_cgsse[df_cgsse['P6040']<15]['FEX_C18'].sum()
print(f'Poblacion que no está en  edad de trabajar: {int(PNET)}')

Poblacion que no está en  edad de trabajar: 11391585

# Calculo de la tasa ocupacion:
- Se necesita calcular primero cantidad de ocupados
- Luego cantidad de PEA
- Por ultimo dividir O/PEA

In [30]:
O = df_o['FEX_C18'].sum()
print(f'Poblacion ocupada: {int(O)}')

PET = df_ft['FEX_C18'].sum()
print(f'Poblacion En edad de trabajar : {int(PET)}')

TO = O/PET
print(f'Tasa de Ocupacion: {TO:.2%}')

Poblacion ocupada: 23752952
Poblacion En edad de trabajar : 40653416
Tasa de Ocupacion: 58.43%

# Calculo de la PEA y la PEI

In [31]:
PEA = df_ft[df_ft['FT']==1.0]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa: {int(PEA)}')

PEI = df_ft[df_ft['FFT']==1]['FEX_C18'].sum()
print(f'Poblacion Economicamente inactiva: {int(PEI)}')

Poblacion Economicamente Activa: 25974846
Poblacion Economicamente inactiva: 14678569

In [32]:
# Cantidad de personas desempleadas
D = df_d['FEX_C18'].sum()
print(f'Poblacion Desempleada: {int(D)}')

TD = D/PEA
print(f'Tasa de Desempleo: {TD*100:.2f}%')

Poblacion Desempleada: 16900463
Tasa de Desempleo: 65.06%

In [33]:
prueba = pd.read_csv('/workspaces/DataAnalyticsUQ/Datos/GEIH2025/No ocupados.CSV',encoding='latin',sep=';')

In [36]:
df_o

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20250626,6,2025,8238974,1,1,1,60,NaN,2,...,3,NaN,3.0,3,NaN,1,950000.0,1,113,6111
1,20250626,6,2025,8238974,1,2,1,60,NaN,2,...,3,NaN,4.0,5,NaN,1,NaN,1,113,6111
2,20250626,6,2025,8238975,1,1,1,60,NaN,2,...,3,NaN,10.0,3,NaN,1,700000.0,1,113,6114
3,20250626,6,2025,8238975,1,3,1,60,NaN,2,...,3,NaN,10.0,3,NaN,1,2000000.0,1,145,6122
4,20250626,6,2025,8238976,1,1,1,60,NaN,2,...,14,NaN,NaN,8,NaN,1,600000.0,1,122,6112
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29701,20250626,6,2025,8283057,1,3,1,60,41.0,1,...,8,NaN,25.0,5,NaN,1,3800000.0,85,8544,2310
29702,20250625,6,2025,8283058,1,1,1,60,NaN,1,...,14,NaN,NaN,2,NaN,1,3000000.0,71,7111,2161
29703,20250625,6,2025,8283058,1,2,1,60,NaN,1,...,3,NaN,10.0,1,NaN,1,1500000.0,47,4752,1420
29704,20250626,6,2025,8283060,1,2,1,60,88.0,1,...,3,NaN,10.0,8,NaN,1,500000.0,56,5619,7512
29705,20250626,6,2025,8283062,1,1,1,60,94.0,1,...,9,NaN,300.0,8,NaN,1,900000.0,3,312,6222

In [37]:
prueba

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P7360,P9460,P1519,P1883,P7422,P7422S1,OFICIO1_C8,OFICIO2_C8,RAMA2D_D_R4,RAMA4D_D_R4
0,20250626,6,2025,8238975,1,2,1,70,NaN,2,...,1.0,2.0,2,NaN,2,NaN,.,6112,1.0,0123
1,20250626,6,2025,8238978,1,1,1,70,NaN,2,...,1.0,2.0,2,NaN,2,NaN,.,9211,1.0,0161
2,20250626,6,2025,8238980,1,2,1,70,NaN,2,...,NaN,NaN,2,NaN,2,NaN,.,.,NaN,.
3,20250626,6,2025,8238981,1,2,1,70,NaN,2,...,NaN,NaN,2,NaN,2,NaN,.,.,NaN,.
4,20250626,6,2025,8238983,1,2,1,70,NaN,2,...,NaN,NaN,2,NaN,2,NaN,.,.,NaN,.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24739,20250626,6,2025,8283056,1,1,1,70,27.0,1,...,10.0,2.0,3,NaN,2,NaN,.,2341,85.0,8530
24740,20250626,6,2025,8283059,1,1,1,70,76.0,1,...,6.0,2.0,2,NaN,2,NaN,5223,5113,55.0,5511
24741,20250626,6,2025,8283060,1,1,1,70,88.0,1,...,9.0,2.0,2,NaN,2,NaN,.,9334,47.0,4711
24742,20250626,6,2025,8283062,1,2,1,70,94.0,1,...,NaN,NaN,2,NaN,2,NaN,.,.,NaN,.
24743,20250626,6,2025,8283062,1,3,1,70,94.0,1,...,NaN,NaN,2,NaN,2,NaN,.,.,NaN,.